# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        defaults:
            web_path: ~

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        squared_thumbnail_small: 
            filters:
                thumbnail:
                    size:          [200, 200]
                    mode:          outbound
                    allow_upscale: true

        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbond }

                background: { size: [124, 94], position: center, color: '#000000' }
                        
