# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_adapter:
            local:
                directory: '%media_path%'
    filesystems:
        public_filesystem:
            adapter: public_adapter
            alias: League\Flysystem\Filesystem
