# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_adapter:
            local:
                location: '%media_path%'
    filesystems:
        public_filesystem:
            adapter: public_adapter
            alias: League\Flysystem\Filesystem
